language: java
jdk: oraclejdk8
dist: trusty

# Make it possible to run tests on a local Chrome
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
# The Following line fixes random Chrome startup failures (https://github.com/SeleniumHQ/docker-selenium/issues/87)
 - export DBUS_SESSION_BUS_ADDRESS=/dev/null

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable


install: true
script: ./.travis.script.sh

deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
    - developer-preview
cache:
  directories:
  - $HOME/.m2
  - .driver
  - selenium_standalone_zips

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/starter/bakery
  
