language: java
jdk: openjdk8
sudo: true
dist: xenial

# Make it possible to run tests on a local Chrome
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable


install: true
script: ./.travis.script.sh

deploy:
  - provider: script
    script: ./.travis.deploy.sh
    skip_cleanup: true
    on:
      branch: master

# Cache requires a master build
branches:
  only:
    - master
    - /^platform-\d{2}$/
    - /^v\d{2}$/
cache:
  directories:
  - $HOME/.m2
  - .driver
  - selenium_standalone_zips

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/starter/bakery

# Notifications
notifications:
  email:
    recipients:
      - haijian@vaadin.com
    on_success: change 
    on_failure: change
